name: main
on: [push]
jobs:
  op:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: op
        run: '"$(wget -O- lesiw.io/ops | sh)"'
